### ISSUE TITLE
Certificate has expired on back.nothingtohide.cc

### ISSUE THREAD

**Issue by donkirkby** [ncase/nothing-to-hide#16]
I really enjoyed the web demo, congratulations on creating a nice set of puzzles that look great.

When I went to the funding page at back.nothingtohide.cc, my browser displayed a warning that the certificate was invalid. Digging a little deeper, I see that it expired on 17 Feb 2015.

**Comment by ncase** [comment]
Thanks! And ack, crap aghhhhhh

Well, the crowdfunding campaign ended, like, over a year ago. So SSL isn't really that important anymore. (i mean, always a good thing to have SSL, but the monthly cost of an SSL endpoint on Heroku was kinda eating into my budget) I'll remove it properly soon. Thanks for catching this!
