### ISSUE TITLE
back.nothoingtohide.cc shouldn't be linked to anymore

### ISSUE THREAD

**Issue by zommuter** [ncase/nothing-to-hide#17]
Since on #16 it is mentioned that the crowdfunding has ended, there should either be no more links to https://back.nothingtohide.cc or you could link to a paypal donation site instead maybe?

**Comment by TazeTSchnitzel** [comment]
HTTPS is broken on that URL.

**Comment by zommuter** [comment]
@TazeTSchnitzel Not broken, the certificate is merely one for `*.herokuapp.com` instead of `*.nothingtohide,cc`, but my point is linking to that site from within the game is rather confusion

**Comment by valioDOTch** [comment]
:+1:

**Comment by TazeTSchnitzel** [comment]
The certificate not matching is what makes it broken. No point in TLS without authentication.

**Comment by ncase** [comment]
The demo links to http:// instead of https:// now! I'll be fixing the main site soon, too. Although it's all kinda moot now, since the project has come to [a bittersweet end](http://eepurl.com/bqvfdb), but thank you all for caring and sticking around. :)
