### ISSUE TITLE
nothingtohide.cc is being used by scammers

### ISSUE THREAD

**Issue by Laurinchen** [ncase/nothing-to-hide#23]
The link nothingtohide.cc (and it's subdomains like back.nothingtohide.cc ) are being used to redirect users to malicious websites. I suspect some scammer bought it after the original domain was freed and now redirects users to scam websites

Some videoproof: https://youtu.be/ap82BknMr0M (The website shown in the vid is only 1 website it redirects to)

I'd replace all links going to this domain with either "[removed]", a info-page mentioning this problem or this issue

**Comment by ncase** [comment]
Hi! Sorry for the super late reply, and thank you for catching this @Laurinchen ! :+1: I've replaced the links with this screen: 
![image](https://user-images.githubusercontent.com/825858/122683841-e546f400-d1cf-11eb-92a1-19ba20b029d0.png)
which links to [this post-mortem](https://web.archive.org/web/20190913052311/https://us3.campaign-archive.com/?u=dfc6ed35d0a2933c059395987&id=47e5a7480f)

At least that's one solution to web privacy:
wait for everything to eventually turn to dust

**Comment by ShaKabosh** [comment]
There is also at least one link to nothingtohide.cc on the <a href="https://ncase.me/sight-and-light/">Sight and Light</a> interactive article, which has not yet been replaced.
